import 'package:flutter/material.dart';

class TaxAssistanceService {
  // ==================== FILING ASSISTANCE ====================

  /// Get step-by-step filing guidance
  static List<FilingStep> getFilingSteps() {
    return [
      FilingStep(
        id: 1,
        title: 'Personal Information',
        description: 'Verify your personal and TIN details',
        icon: Icons.person,
        tips: [
          'Ensure your TIN number is correct',
          'Verify your assessment year',
          'Check your filing type (Original/Revised/Belated)',
        ],
        validationRules: [
          'TIN must be 9 digits',
          'Assessment year must be valid',
          'Filing type must be selected',
        ],
      ),
      FilingStep(
        id: 2,
        title: 'Income Declaration',
        description: 'Declare all your income sources',
        icon: Icons.attach_money,
        tips: [
          'Include all employment income',
          'Declare business income if applicable',
          'Don\'t forget rental and agricultural income',
          'Report capital gains if any',
        ],
        validationRules: [
          'Total income must be > 0',
          'Employment income is required for PAYE',
          'Business income requires TIN registration',
        ],
      ),
      FilingStep(
        id: 3,
        title: 'Claim Deductions',
        description: 'Claim eligible deductions and reliefs',
        icon: Icons.card_giftcard,
        tips: [
          'Personal Relief - TSh 270,000 automatically applied',
          'Pension contributions are deductible',
          'Insurance premiums (Life, Health) are deductible',
          'Medical expenses up to TSh 100,000',
          'Charitable donations to registered organizations',
        ],
        validationRules: [
          'Total deductions cannot exceed total income',
          'Medical expenses require receipts',
          'Charitable donations require organization registration',
        ],
      ),
      FilingStep(
        id: 4,
        title: 'Tax Calculation',
        description: 'Review your tax calculation',
        icon: Icons.calculate,
        tips: [
          'PAYE rates range from 0% to 35%',
          'Skills Development Levy is 5%',
          'Railway Development Levy is 5%',
          'Cess is 4% of tax payable',
        ],
        validationRules: [
          'Tax payable must be calculated',
          'All levies must be included',
          'Total liability must match calculation',
        ],
      ),
      FilingStep(
        id: 5,
        title: 'Payment & Submission',
        description: 'Make payment and submit to TRA',
        icon: Icons.payment,
        tips: [
          'Payment can be made via M-Pesa, Tigo Pesa, Airtel Money',
          'Bank transfer is also accepted',
          'Control number is generated after payment',
          'Keep your acknowledgment number for reference',
        ],
        validationRules: [
          'Payment must be completed before submission',
          'Control number is required',
          'Acknowledgment number is generated by TRA',
        ],
      ),
    ];
  }

  /// Get field-specific assistance
  static String getFieldAssistance(String fieldName) {
    final assistanceMap = {
      'employmentIncome':
          'Enter your total employment income including bonuses, allowances, and benefits. This is used to calculate PAYE tax.',
      'businessIncome':
          'Enter your business or professional income. You must have a valid TIN registered for business.',
      'rentalIncome':
          'Enter income from rental properties. Deductible expenses include maintenance, insurance, and interest on mortgage.',
      'agriculturalIncome':
          'Enter income from farming or agricultural activities.',
      'capitalGains':
          'Enter gains from sale of assets like land, buildings, or shares.',
      'interestIncome':
          'Enter interest earned from savings accounts, bonds, or other investments.',
      'dividendIncome': 'Enter dividends received from shares and investments.',
      'pensionRelief':
          'Enter pension contributions made during the year. These are deductible up to certain limits.',
      'insuranceRelief':
          'Enter insurance premiums paid (Life Insurance, Health Insurance).',
      'medicalExpenses':
          'Enter medical expenses incurred. Keep all receipts for verification.',
      'charitableDonations':
          'Enter donations made to registered charitable organizations. Must have official receipts.',
      'educationExpenses': 'Enter education expenses including tuition fees.',
      'mortgageInterest':
          'Enter interest paid on home loans. Requires bank statements.',
      'businessExpenses':
          'Enter business expenses claimed against business income.',
    };
    return assistanceMap[fieldName] ??
        'Enter the required amount for this field.';
  }

  /// Validate filing data
  static FilingValidationResult validateFiling(
      Map<String, dynamic> filingData) {
    final errors = <String>[];
    final warnings = <String>[];
    final suggestions = <String>[];

    // Validate TIN
    final tinNumber = filingData['tinNumber']?.toString().trim() ?? '';
    if (tinNumber.isEmpty) {
      errors.add('TIN number is required');
    } else if (tinNumber.length != 9) {
      errors.add('TIN number must be exactly 9 digits');
    }

    // Validate income
    final totalIncome = _parseDouble(filingData['totalIncome']);
    if (totalIncome <= 0) {
      errors.add('Total income must be greater than zero');
    }

    // Validate employment income
    final employmentIncome = _parseDouble(filingData['employmentIncome']);
    if (employmentIncome > 0) {
      suggestions.add(
          'You have employment income. Ensure your employer has deducted PAYE correctly.');
    }

    // Validate business income
    final businessIncome = _parseDouble(filingData['businessIncome']);
    if (businessIncome > 0) {
      suggestions.add(
          'You have business income. Ensure you are registered for business taxes.');
      if (businessIncome > 10000000) {
        warnings.add(
            'Business income exceeds TSh 10,000,000. You may need to register for VAT.');
      }
    }

    // Validate deductions
    final totalDeductions = _parseDouble(filingData['totalDeductions']);
    if (totalDeductions > totalIncome) {
      errors.add('Total deductions cannot exceed total income');
    }

    // Validate medical expenses
    final medicalExpenses = _parseDouble(filingData['medicalExpenses']);
    if (medicalExpenses > 100000) {
      suggestions.add(
          'Medical expenses above TSh 100,000 may require additional documentation.');
    }

    // Validate charitable donations
    final charitableDonations = _parseDouble(filingData['charitableDonations']);
    if (charitableDonations > 0) {
      suggestions.add(
          'Charitable donations require official receipts from registered organizations.');
    }

    return FilingValidationResult(
      isValid: errors.isEmpty,
      errors: errors,
      warnings: warnings,
      suggestions: suggestions,
    );
  }

  static double _parseDouble(dynamic value) {
    if (value == null) return 0.0;
    if (value is double) return value;
    if (value is int) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    return 0.0;
  }
}

// ==================== MODELS ====================

class FilingStep {
  final int id;
  final String title;
  final String description;
  final IconData icon;
  final List<String> tips;
  final List<String> validationRules;

  FilingStep({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.tips,
    required this.validationRules,
  });
}

class FilingValidationResult {
  final bool isValid;
  final List<String> errors;
  final List<String> warnings;
  final List<String> suggestions;

  FilingValidationResult({
    required this.isValid,
    required this.errors,
    required this.warnings,
    required this.suggestions,
  });
}
